- README.md
- demo/visualization/src/App.tsx
- package.json
* Hardware:
* Toolchain:
* SDK:
> Improve readme

- README.md
- demo/blueprint/package.json
- demo/visualization/src/App.tsx
- package.json
- packages/core/package.json
- packages/dynamodb-event-storage-adapter/package.json
- packages/inmemory-event-storage-adapter/package.json
- packages/json-schema-event/package.json
- packages/test-tools/package.json
- packages/zod-event/package.json
* Hardware:
* Toolchain:
* SDK:
> Update package json homepages

- demo/blueprint/package.json
- packages/core/package.json
- packages/dynamodb-event-storage-adapter/package.json
- packages/inmemory-event-storage-adapter/package.json
- packages/json-schema-event/package.json
- packages/test-tools/package.json
- packages/zod-event/package.json
* Hardware:
* Toolchain:
* SDK:
> Update castore repository

- demo/blueprint/src/counters/index.ts
- demo/blueprint/src/counters/mock.ts
- packages/core/src/eventStore.ts
- packages/core/src/index.ts
- packages/inmemory-event-storage-adapter/src/inMemory.ts
- packages/inmemory-event-storage-adapter/src/inMemory.unit.test.ts
- packages/json-schema-command/src/jsonSchema.util.test.ts
- packages/test-tools/src/mockEventStore.ts
- packages/test-tools/src/mockEventStore.type.test.ts
- packages/test-tools/src/mockEventStore.unit.test.ts
- packages/test-tools/src/mockedEventStore.ts
* Hardware:
* Toolchain:
* SDK:
> feature: improvement of mockEventStore

- packages/dynamodb-event-storage-adapter/src/dynamoDb.ts
* Hardware:
* Toolchain:
* SDK:
> fix: fix bug in dynamodb adapter

- packages/dynamodb-event-storage-adapter/src/dynamoDb.ts
* Hardware:
* Toolchain:
* SDK:
> feature: Enable settings DynamoDB table name dynamically

- packages/core/src/command/command.ts
- packages/core/src/event/eventDetail.ts
- packages/core/src/event/eventDetail.type.test.ts
- packages/core/src/event/eventType.ts
- packages/core/src/event/eventType.type.test.ts
- packages/core/src/eventStore/eventStore.ts
- packages/core/src/eventStore/eventStore.util.test.ts
- packages/core/src/eventStore/generics.ts
- packages/json-schema-command/src/jsonSchema.ts
- packages/json-schema-command/src/jsonSchema.util.test.ts
- packages/json-schema-event/package.json
- packages/json-schema-event/src/jsonSchema.ts
- packages/json-schema-event/src/jsonSchema.unit.test.ts
- packages/zod-event/package.json
- packages/zod-event/src/zodEvent.ts
- packages/zod-event/src/zodEvent.unit.test.ts
* Hardware:
* Toolchain:
* SDK:
> feature: rework EventDetail for more simplicity

- README.md
- packages/core/src/command/command.ts
- packages/core/src/eventStore/eventStore.ts
- packages/core/src/eventStore/types.ts
- packages/core/src/index.ts
- packages/core/src/utils.ts
- packages/json-schema-command/src/jsonSchema.ts
- packages/test-tools/src/mockedEventStore.ts
* Hardware:
* Toolchain:
* SDK:
> feature: Improve documentation

- README.md
- docs/building-your-own-event-storage-adapter.md
- docs/the-five-rules-of-event-sourcing.md
- packages/core/src/eventStore/eventStore.ts
- packages/core/src/eventStore/eventStore.type.test.ts
- packages/core/src/eventStore/types.ts
- packages/core/src/index.ts
- packages/dynamodb-event-storage-adapter/README.md
- packages/dynamodb-event-storage-adapter/src/utils/pushEventsTransaction.ts
- packages/inmemory-event-storage-adapter/README.md
- packages/json-schema-event/README.md
- packages/zod-event/README.md
* Hardware:
* Toolchain:
* SDK:
> fix: (Almost) Finish readme

- README.md
- docs/building-your-own-event-storage-adapter.md
* Hardware:
* Toolchain:
* SDK:
> chore: add documentation on storage adapters

- README.md
* Hardware:
* Toolchain:
* SDK:
> chore: finish readme

- README.md
- packages/json-schema-event/README.md
- packages/json-schema-event/package.json
- packages/zod-event/README.md
- packages/zod-event/package.json
* Hardware:
* Toolchain:
* SDK:
> chore: document event types

- README.md
- packages/json-schema-command/README.md
- packages/json-schema-command/package.json
- packages/json-schema-event/README.md
- packages/zod-event/README.md
* Hardware:
* Toolchain:
* SDK:
> chore: document json-schema-command package

- packages/json-schema-command/README.md
- packages/zod-event/README.md
* Hardware:
* Toolchain:
* SDK:
> fix: fix typos in READMEs

- README.md
- demo/visualization/src/components/EventStoreSynchronizer.tsx
- demo/visualization/src/components/error.ts
- docs/building-your-own-event-storage-adapter.md
- packages/core/src/errors/eventAlreadyExists.ts
- packages/core/src/index.ts
- packages/dynamodb-event-storage-adapter/README.md
- packages/dynamodb-event-storage-adapter/package.json
- packages/dynamodb-event-storage-adapter/src/dynamoDb.ts
- packages/dynamodb-event-storage-adapter/src/error.ts
- packages/inmemory-event-storage-adapter/README.md
- packages/inmemory-event-storage-adapter/package.json
- packages/inmemory-event-storage-adapter/src/error.ts
- packages/inmemory-event-storage-adapter/src/inMemory.ts
- packages/inmemory-event-storage-adapter/src/inMemory.unit.test.ts
- packages/json-schema-command/src/jsonSchema.ts
- packages/json-schema-command/src/jsonSchema.unit.test.ts
- packages/json-schema-command/src/jsonSchema.util.test.ts
* Hardware:
* Toolchain:
* SDK:
> chore: Document event storage adapters

- packages/core/src/index.ts
* Hardware:
* Toolchain:
* SDK:
> fix: fix bug in EventAlreadyExistsError export

- README.md
- packages/inmemory-event-storage-adapter/README.md
* Hardware:
* Toolchain:
* SDK:
> fix: fix mistakes in documentation

- packages/test-tools/README.md
- packages/test-tools/src/index.ts
- packages/test-tools/src/muteEventStore.ts
- packages/test-tools/src/muteEventStore.type.test.ts
- packages/test-tools/src/muteEventStore.unit.test.ts
* Hardware:
* Toolchain:
* SDK:
> feature: create muteEventStore util in test-tools

- packages/test-tools/README.md
* Hardware:
* Toolchain:
* SDK:
> fix: improve the test tools documentation

- README.md
- package.json
* Hardware:
* Toolchain:
* SDK:
> fix: use toggles for tech descriptions in README

- package.json
- packages/dynamodb-event-storage-adapter/package.json
- packages/dynamodb-event-storage-adapter/src/dynamoDb.ts
- packages/inmemory-event-storage-adapter/package.json
- packages/inmemory-event-storage-adapter/src/inMemory.ts
- packages/redux-event-storage-adapter/package.json
- yarn.lock
* Hardware:
* Toolchain:
* SDK:
> fix: remove lodash from dependencies

- README.md
- demo/blueprint/src/commands/createCounter.ts
- demo/blueprint/src/commands/createUser.ts
- demo/blueprint/src/commands/deleteUser.ts
- demo/blueprint/src/commands/incrementCounter.ts
- demo/blueprint/src/counters/mock.ts
- packages/core/src/command/command.util.test.ts
- packages/core/src/eventStore/eventStore.type.test.ts
- packages/core/src/eventStore/eventStore.util.test.ts
- packages/core/src/eventStore/types.ts
- packages/core/src/storageAdapter.ts
- packages/dynamodb-event-storage-adapter/src/dynamoDb.ts
- packages/inmemory-event-storage-adapter/package.json
- packages/inmemory-event-storage-adapter/src/inMemory.ts
- packages/inmemory-event-storage-adapter/src/inMemory.unit.test.ts
- packages/json-schema-command/src/jsonSchema.util.test.ts
- packages/redux-event-storage-adapter/src/reduxAdapter.ts
- packages/test-tools/package.json
- packages/test-tools/src/mockEventStore.unit.test.ts
- packages/test-tools/src/muteEventStore.unit.test.ts
- yarn.lock
* Hardware:
* Toolchain:
* SDK:
> feature: Remove timestamp from pushEvent input (set it automatically)

- demo/blueprint/package.json
- demo/blueprint/src/commands/createCounter.ts
- demo/blueprint/src/commands/createUser.ts
- demo/implementation/functions/createCounter/handler.ts
- demo/implementation/functions/createUser/handler.ts
- demo/visualization/src/App.tsx
- demo/visualization/src/index.tsx
- demo/visualization/src/tabs/Commands/CommandCard.tsx
- demo/visualization/src/tabs/Commands/index.tsx
- demo/visualization/src/tabs/DB/index.tsx
- packages/core/src/command/command.ts
- packages/core/src/command/command.type.test.ts
- packages/core/src/command/command.unit.test.ts
- packages/core/src/command/command.util.test.ts
- packages/core/src/index.ts
- packages/json-schema-command/src/jsonSchema.ts
- packages/json-schema-command/src/jsonSchema.type.test.ts
- packages/json-schema-command/src/jsonSchema.util.test.ts
- yarn.lock
* Hardware:
* Toolchain:
* SDK:
> feature: Enable context in commands

- .github/FUNDING.yml
* Hardware:
* Toolchain:
* SDK:
> fix: add sponsor button

- packages/dynamodb-event-storage-adapter/README.md
- packages/inmemory-event-storage-adapter/README.md
- packages/json-schema-command/README.md
- packages/json-schema-event/README.md
- packages/redux-event-storage-adapter/README.md
- packages/redux-event-storage-adapter/src/configureCastore.ts
- packages/redux-event-storage-adapter/src/errors/eventStoreReduxStateNotFound.ts
- packages/redux-event-storage-adapter/src/errors/index.ts
- packages/redux-event-storage-adapter/src/errors/reduxEventStorageAdapterNotFound.ts
- packages/redux-event-storage-adapter/src/getCastoreReducers.ts
- packages/redux-event-storage-adapter/src/hooks/useAggregateEvents.ts
- packages/redux-event-storage-adapter/src/hooks/useAggregateIds.ts
- packages/redux-event-storage-adapter/src/index.ts
- packages/redux-event-storage-adapter/src/reduxAdapter.ts
- packages/redux-event-storage-adapter/src/utils/getEventStoreSliceName.ts
- packages/test-tools/README.md
- packages/zod-event/README.md
* Hardware:
* Toolchain:
* SDK:
> fix: Document redux event storage adapter

- README.md
- packages/test-tools/README.md
* Hardware:
* Toolchain:
* SDK:
> fix: improve documentation

- packages/in-memory-message-bus-adapter/README.md
* Hardware:
* Toolchain:
* SDK:
> fix: typo in docs

- packages/redux-event-storage-adapter/README.md
Fix a spelling error and slightly improve grammar.
By reading the corrected version of the README.
> fix: wording in docs

- packages/in-memory-message-bus-adapter/src/inMemory.ts
- packages/in-memory-message-bus-adapter/src/inMemory.unit.test.ts
- packages/in-memory-message-bus-adapter/src/message.ts
- packages/in-memory-message-bus-adapter/src/types.ts
- packages/in-memory-message-bus-adapter/src/utils.ts
- packages/in-memory-message-queue-adapter/src/queue.ts
- packages/in-memory-message-queue-adapter/src/queue.unit.test.ts
- packages/in-memory-message-queue-adapter/src/utils.ts
* Hardware:
* Toolchain:
* SDK:
> fix: Add retry policy to in memory message bus and queue

- packages/dynamodb-event-storage-adapter/README.md
- packages/event-bridge-message-bus-adapter/README.md
- packages/sqs-message-queue-adapter/README.md
* Hardware:
* Toolchain:
* SDK:
> fix: docs typos

- README.md
- packages/core/src/index.ts
- packages/core/src/messaging/bus/generics.ts
- packages/core/src/messaging/bus/index.ts
- packages/core/src/messaging/queue/generics.ts
- packages/core/src/messaging/queue/index.ts
- packages/in-memory-message-bus-adapter/README.md
- packages/in-memory-message-bus-adapter/src/inMemory.unit.test.ts
- packages/in-memory-message-queue-adapter/README.md
- packages/in-memory-message-queue-adapter/src/queue.ts
- packages/in-memory-message-queue-adapter/src/queue.unit.test.ts
- packages/inmemory-event-storage-adapter/README.md
- packages/test-tools/README.md
* Hardware:
* Toolchain:
* SDK:
> fix: Document last messaging packages

- packages/core/src/eventStore/eventStore.ts
- packages/core/src/eventStore/eventStore.unit.test.ts
- packages/core/src/storageAdapter.ts
- packages/dynamodb-event-storage-adapter/src/adapter.ts
- packages/dynamodb-event-storage-adapter/src/adapter.unit.test.ts
- packages/dynamodb-event-storage-adapter/src/utils/parseAppliedListAggregateIdsOptions.ts
- packages/inmemory-event-storage-adapter/src/adapter.ts
- packages/inmemory-event-storage-adapter/src/adapter.unit.test.ts
- packages/inmemory-event-storage-adapter/src/utils/parseAppliedListAggregateIdsOptions.ts
- packages/redux-event-storage-adapter/src/adapter.ts
- packages/redux-event-storage-adapter/src/hooks/useAggregateIds.ts
- packages/redux-event-storage-adapter/src/utils/parseAppliedListAggregateIdsOptions.ts
* Hardware:
* Toolchain:
* SDK:
> feature: Support initial event date filtering and reverse options in list aggregate ids

- README.md
- docs/building-your-own-event-storage-adapter.md
- docs/the-five-rules-of-event-sourcing.md
* Hardware:
* Toolchain:
* SDK:
> fix: update documentation

- packages/core/src/messaging/message.ts
- packages/in-memory-message-bus-adapter/src/message.ts
* Hardware:
* Toolchain:
* SDK:
> fix: rework types following real life usage pbs

- README.md
- packages/core/src/command/command.type.test.ts
- packages/core/src/command/command.unit.test.ts
- packages/core/src/connectedEventStore/connectedEventStore.ts
- packages/core/src/connectedEventStore/connectedEventStore.type.test.ts
- packages/core/src/connectedEventStore/connectedEventStore.unit.test.ts
- packages/core/src/connectedEventStore/connectedEventStore.util.test.ts
- packages/core/src/connectedEventStore/index.ts
- packages/core/src/eventStore/eventStore.ts
- packages/core/src/eventStore/eventStore.type.test.ts
- packages/core/src/eventStore/eventStore.unit.test.ts
- packages/core/src/eventStore/eventStore.util.test.ts
- packages/core/src/eventStore/types.ts
- packages/core/src/index.ts
- packages/core/src/messaging/bus/notificationMessageBus.ts
- packages/core/src/messaging/bus/stateCarryingMessageBus.ts
- packages/core/src/messaging/queue/notificationMessageQueue.ts
- packages/core/src/messaging/queue/notificationMessageQueue.type.test.ts
- packages/core/src/messaging/queue/notificationMessageQueue.util.test.ts
- packages/core/src/messaging/queue/stateCarryingMessageQueue.ts
- packages/json-schema-command/src/command.type.test.ts
* Hardware:
* Toolchain:
* SDK:
> feature: Create connected event store class

- packages/dynamodb-event-storage-adapter/package.json
* Hardware:
* Toolchain:
* SDK:
> fix: remove dynamodb dependency from dynamodb event storage adapter

- packages/core/src/messaging/queue/messageQueueAdapter.ts
- packages/core/src/messaging/queue/notificationMessageQueue.ts
- packages/core/src/messaging/queue/stateCarryingMessageQueue.ts
- packages/in-memory-message-queue-adapter/src/adapter.ts
- packages/in-memory-message-queue-adapter/src/adapter.unit.test.ts
- packages/sqs-message-queue-adapter/package.json
- packages/sqs-message-queue-adapter/src/adapter.ts
- packages/sqs-message-queue-adapter/src/adapter.unit.test.ts
- yarn.lock
This adds publishMessages to MessageQueueAdapter.
It addresses the queue part of Issue #69
New feature (non-breaking change which adds functionality)
Unit tests
> feature: add publishMessages to MessageQueueAdapter

- README.md
- packages/core/src/messaging/bus/messageBusAdapter.ts
- packages/core/src/messaging/bus/notificationMessageBus.ts
- packages/core/src/messaging/bus/stateCarryingMessageBus.ts
- packages/event-bridge-message-bus-adapter/package.json
- packages/event-bridge-message-bus-adapter/src/adapter.ts
- packages/event-bridge-message-bus-adapter/src/adapter.unit.test.ts
- packages/in-memory-message-bus-adapter/src/adapter.ts
- packages/in-memory-message-bus-adapter/src/adapter.unit.test.ts
- packages/in-memory-message-queue-adapter/src/adapter.unit.test.ts
- yarn.lock
This adds publishMessages to MessageQueueAdapter
Fixes #69 
Unit tests
> feature: add publishMessages to MessageBusAdapter

- .github/actions/get-affected-packages-paths/action.yml
- .github/actions/get-affected-packages-paths/get-affected-paths.sh
- .github/actions/install-node-modules/action.yml
- .github/actions/lint-and-tests/action.yml
- .github/actions/package/action.yml
- .github/workflows/test-pr.yml
- nx.json
This is to test only affected libs on pr opened, synchronized, and reopened.
Fixes #73
Improving DX for castore maintainers.
> feature: test only affected libs

- packages/core/src/messaging/bus/generics.ts
- packages/core/src/messaging/queue/generics.ts
- packages/core/src/messaging/queue/stateCarryingMessageQueue.fixtures.test.ts
- packages/event-bridge-message-bus-adapter/src/message.ts
- packages/in-memory-message-bus-adapter/src/adapter.ts
- packages/in-memory-message-bus-adapter/src/types.ts
- packages/in-memory-message-queue-adapter/src/adapter.ts
- packages/sqs-message-queue-adapter/src/message.ts
* Hardware:
* Toolchain:
* SDK:
> fix: bug in message bus and queue types

- .github/workflows/deploy-prototype.yml
- demo/visualization/package.json
- demo/visualization/vite.config.ts
Fixes #75 
* Hardware:
* Toolchain:
* SDK:
> feature: add visualization in github pages

- demo/blueprint/src/commands/catchPokemon.ts
- packages/core/dependency-cruiser.js
- packages/core/src/command/command.fixtures.test.ts
- packages/core/src/connectedEventStore/connectedEventStore.ts
- packages/core/src/connectedEventStore/connectedEventStore.unit.test.ts
- packages/core/src/event/groupedEvent.ts
- packages/core/src/eventStore/eventStore.fixtures.test.ts
- packages/core/src/eventStore/eventStore.ts
- packages/core/src/eventStore/eventStore.type.test.ts
- packages/core/src/eventStore/eventStore.unit.test.ts
- packages/core/src/eventStore/types.ts
- packages/core/src/index.ts
- packages/core/src/storageAdapter.ts
- packages/dynamodb-event-storage-adapter/src/adapter.ts
- packages/inmemory-event-storage-adapter/src/adapter.ts
- packages/json-schema-command/src/command.fixtures.test.ts
- packages/redux-event-storage-adapter/src/adapter.ts
* Hardware:
* Toolchain:
* SDK:
> feature: Redefine event groups api

- packages/core/src/event/groupedEvent.ts
- packages/core/src/eventStore/eventStore.ts
- packages/core/src/eventStore/eventStore.unit.test.ts
- packages/core/src/index.ts
- packages/core/src/storageAdapter.ts
- packages/dynamodb-event-storage-adapter/src/adapter.ts
- packages/dynamodb-event-storage-adapter/src/adapter.unit.test.ts
- packages/inmemory-event-storage-adapter/src/adapter.ts
- packages/inmemory-event-storage-adapter/src/adapter.unit.test.ts
- packages/redux-event-storage-adapter/src/adapter.ts
* Hardware:
* Toolchain:
* SDK:
> feature: add eventStore context to storage adapter functions

- demo/implementation/functions/catchPokemon/catchPokemon.unit.test.ts
- demo/implementation/package.json
- demo/implementation/vite.config.js
- packages/inmemory-event-storage-adapter/src/adapter.ts
- packages/redux-event-storage-adapter/src/adapter.ts
- packages/redux-event-storage-adapter/src/getCastoreReducers.ts
- yarn.lock
* Hardware:
* Toolchain:
* SDK:
> feature: Implement event groups in redux storage adapter

- packages/dynamodb-event-storage-adapter/src/adapter.ts
- packages/inmemory-event-storage-adapter/src/adapter.ts
- packages/redux-event-storage-adapter/src/adapter.ts
* Hardware:
* Toolchain:
* SDK:
> patch: Implement event groups in dynamodb event storage adapter

- packages/dynamodb-event-storage-adapter/package.json
- packages/dynamodb-event-storage-adapter/src/adapter.ts
- packages/dynamodb-event-storage-adapter/src/adapter.unit.test.ts
- packages/dynamodb-event-storage-adapter/src/constants.ts
- packages/dynamodb-event-storage-adapter/src/index.ts
- packages/dynamodb-event-storage-adapter/src/singleTableAdapter.ts
- packages/dynamodb-event-storage-adapter/src/singleTableAdapter.unit.test.ts
- packages/dynamodb-event-storage-adapter/src/utils/formatEventForTransaction.ts
- packages/dynamodb-event-storage-adapter/src/utils/isConditionalCheckFailed.ts
- packages/dynamodb-event-storage-adapter/src/utils/pushEventsTransaction.ts
- yarn.lock
* Hardware:
* Toolchain:
* SDK:
> feature: Create single table dynamodb event storage adapter

- .github/actions/install-node-modules/action.yml
- .github/workflows/deploy-prototype.yml
- .github/workflows/release-to-npm.yml
* Hardware:
* Toolchain:
* SDK:
> chore: fix github actions warning

- packages/core/package.json
* Hardware:
* Toolchain:
* SDK:
> fix: set ts-toolbelt as dependency in core

- packages/dynamodb-event-storage-adapter/README.md
* Hardware:
* Toolchain:
* SDK:
> patch: document dynamodb single table event storage adpater

- packages/dynamodb-event-storage-adapter/README.md
- packages/dynamodb-event-storage-adapter/src/adapter.ts
- packages/dynamodb-event-storage-adapter/src/index.ts
- packages/dynamodb-event-storage-adapter/src/singleTableAdapter.ts
- packages/dynamodb-event-storage-adapter/src/utils/imageParser.ts
- packages/dynamodb-event-storage-adapter/src/utils/pushEventsTransaction.unit.test.ts
- packages/dynamodb-event-storage-adapter/tsconfig.json
* Hardware:
* Toolchain:
* SDK:
> patch: export ImageParser class from dynamodb-event-storage-adapter

- packages/dynamodb-event-storage-adapter/tsconfig.json
- packages/in-memory-message-bus-adapter/src/adapter.ts
- packages/in-memory-message-bus-adapter/src/adapter.unit.test.ts
- packages/in-memory-message-queue-adapter/src/adapter.unit.test.ts
- packages/react-visualizer/src/tabs/DB/AggregateCard.tsx
- packages/react-visualizer/src/tabs/DB/index.tsx
- tsconfig.json
* Hardware:
* Toolchain:
* SDK:
> chore: Add no unchecked indexed access ts option

- packages/react-visualizer/README.md
* Hardware:
* Toolchain:
* SDK:
> patch: Add minimal docs to react visualizer

- package.json
- packages/dynamodb-event-storage-adapter/src/adapter.ts
- scripts/setPackagesVersions.ts
* Hardware:
* Toolchain:
* SDK:
> patch: tag previous dynamodb storage adapter as deprecated

- .eslintrc.js
- demo/blueprint/package.json
- packages/react-visualizer/src/components/Form.ts
* Hardware:
* Toolchain:
* SDK:
> patch: detect badly declared dependencies

- README.md
- packages/core/dependency-cruiser.js
- packages/core/src/connectedEventStore/connectedEventStore.ts
- packages/core/src/connectedEventStore/connectedEventStore.unit.test.ts
- packages/core/src/connectedEventStore/publishPushedEvent.ts
- packages/core/src/connectedEventStore/publishPushedEvent.unit.test.ts
- packages/core/src/eventStore/eventStore.ts
- packages/core/src/eventStore/types.ts
- packages/core/src/messaging/bus/errors/undefinedMessageBusAdapter.ts
- packages/core/src/messaging/index.ts
- packages/core/src/messaging/messageChannel.ts
- packages/core/src/messaging/queue/errors/undefinedMessageQueueAdapter.ts
Fixes https://github.com/castore-dev/castore/issues/104
> patch: Make connected event store class publish messages after pushing event groups

- packages/react-visualizer/README.md
Fixes https://github.com/castore-dev/castore/issues/71
> patch: document react visualizer

- README.md
- packages/react-visualizer/README.md
* Hardware:
* Toolchain:
* SDK:
> patch: docs

- README.md
- packages/dam/README.md
- packages/dam/package.json
- packages/dam/src/pourAggregateEvents/index.ts
- packages/dam/src/pourAggregateEvents/pourAggregateEvents.ts
- packages/dam/src/pourAggregateEvents/pourAggregateEvents.unit.test.ts
- packages/dam/src/pourEventStoreAggregateIds/pourEventStoreAggregateIds.ts
- packages/dam/src/pourEventStoreAggregateIds/pourEventStoreAggregateIds.unit.test.ts
- packages/dam/src/pourEventStoreEvents/eventBook.ts
- packages/dam/src/pourEventStoreEvents/pourEventStoreEvents.ts
- packages/dam/src/pourEventStoreEvents/pourEventStoreEvents.unit.test.ts
- packages/dam/src/utils.ts
- packages/dam/vite.config.js
- packages/inmemory-event-storage-adapter/README.md
- packages/react-visualizer/README.md
- packages/test-tools/README.md
- yarn.lock
* Hardware:
* Toolchain:
* SDK:
> feature: Document dam library

- packages/dam/README.md
- packages/dam/src/fixtures.test.ts
- packages/dam/src/index.ts
- packages/dam/src/pourAggregateEvents/pourAggregateEvents.ts
- packages/dam/src/pourAggregateEvents/pourAggregateEvents.unit.test.ts
- packages/dam/src/pourEventStoreAggregateIds/pourEventStoreAggregateIds.unit.test.ts
- packages/dam/src/pourEventStoreCollectionEvents/index.ts
- packages/dam/src/pourEventStoreCollectionEvents/pourEventStoreCollectionEvents.ts
- packages/dam/src/pourEventStoreCollectionEvents/pourEventStoreCollectionEvents.unit.test.ts
- packages/dam/src/pourEventStoreEvents/pourEventStoreEvents.ts
- packages/dam/src/pourEventStoreEvents/pourEventStoreEvents.unit.test.ts
- packages/dam/src/utils/eventBook.ts
- packages/dam/src/utils/getIsBetween.ts
- packages/dam/src/utils/isBetween.ts
- packages/dam/src/utils/messageBatch.ts
- packages/dam/src/utils/messagePourer.ts
* Hardware:
* Toolchain:
* SDK:
> patch: create pourEventStoreCollectionEvents util

- packages/dam/README.md
* Hardware:
* Toolchain:
* SDK:
> patch: document pourEventStoreCollectionEvents

- docs/docs/1-introduction.md
- docs/docs/3-the-basics.md
- docs/docs/4-advanced-usage.md
- docs/docusaurus.config.js
- docs/package.json
- docs/src/pages/index.tsx
* Hardware:
* Toolchain:
* SDK:
> docs: add docsearch

- packages/event-bridge-s3-message-bus-adapter/src/adapter.ts
* Hardware:
* Toolchain:
* SDK:
> fix: small fix in event bridge and s3 message bus adapter

- scripts/setPackagesVersions.ts
Fixes https://github.com/castore-dev/castore/issues/118
> fix: bug in setPackagesVersions script

- docs/docs/3-event-sourcing/1-events.md
- docs/docs/3-event-sourcing/3-event-stores.md
- docs/docs/3-event-sourcing/5-pushing-events.md
- docs/docs/4-reacting-to-events/2-message-queues.md
- docs/docs/4-reacting-to-events/3-message-buses.md
- docs/docs/4-reacting-to-events/4-connected-event-store.md
* Hardware:
* Toolchain:
* SDK:
> patch: improve references sections

- README.md
- docs/src/css/custom.css
- docs/src/pages/index.tsx
Display footer links nicely. Make the footer responsive.
Local testing.
* Hardware: macbook, chrome
* Toolchain:
* SDK:
- [] I have commented my code, particularly in hard-to-understand areas
> chore: improve footer UI

- packages/message-bus-adapter-in-memory/README.md
- packages/message-bus-adapter-in-memory/package.json
- packages/message-bus-adapter-in-memory/project.json
- yarn.lock
* Hardware:
* Toolchain:
* SDK:
> fix: last naming

- packages/command-json-schema/src/command.fixtures.test.ts
- packages/core/src/command/command.fixtures.test.ts
- packages/core/src/connectedEventStore/connectedEventStore.unit.test.ts
- packages/core/src/event/eventType.ts
- packages/core/src/eventStorageAdapter.ts
- packages/core/src/eventStore/eventStore.fixtures.test.ts
- packages/core/src/eventStore/eventStore.unit.test.ts
- packages/event-storage-adapter-dynamodb/src/legacyAdapter.ts
- packages/event-storage-adapter-dynamodb/src/singleTableAdapter.ts
- packages/event-storage-adapter-in-memory/src/adapter.ts
- packages/event-storage-adapter-redux/src/adapter.ts
* Hardware:
* Toolchain:
* SDK:
> fix: remove any mention of snapshots

- .github/workflows/label-pr.yml
- docs/docs/2-event-sourcing/6-joining-data.md
- docs/docs/3-reacting-to-events/4-connected-event-store.md
- packages/core/src/eventStorageAdapter.ts
- packages/core/src/eventStore/eventStore.ts
- packages/core/src/eventStore/eventStore.type.test.ts
- packages/core/src/eventStore/eventStore.unit.test.ts
- packages/core/src/eventStore/types.ts
- packages/event-storage-adapter-dynamodb/src/legacyAdapter.ts
- packages/event-storage-adapter-dynamodb/src/singleTableAdapter.ts
- packages/event-storage-adapter-in-memory/src/adapter.ts
- packages/event-storage-adapter-in-memory/src/adapter.unit.test.ts
- packages/event-storage-adapter-redux/src/adapter.ts
* Hardware:
* Toolchain:
* SDK:
> feature: Enable passing options to push event group

- packages/core/src/eventStorageAdapter.ts
- packages/core/src/messaging/message.ts
- packages/event-storage-adapter-dynamodb/src/legacyAdapter.ts
- packages/event-storage-adapter-dynamodb/src/legacyAdapter.unit.test.ts
- packages/event-storage-adapter-dynamodb/src/singleTableAdapter.ts
- packages/event-storage-adapter-dynamodb/src/singleTableAdapter.unit.test.ts
- packages/event-storage-adapter-in-memory/src/adapter.ts
- packages/event-storage-adapter-in-memory/src/adapter.unit.test.ts
- packages/event-storage-adapter-in-memory/src/utils/parseAppliedListAggregateIdsOptions.ts
- packages/event-storage-adapter-redux/src/adapter.ts
- packages/event-storage-adapter-redux/src/hooks/useAggregateIds.ts
- packages/event-storage-adapter-redux/src/utils/parseAppliedListAggregateIdsOptions.ts
- packages/lib-dam/src/pourEventStoreAggregateIds/pourEventStoreAggregateIds.ts
- packages/lib-dam/src/pourEventStoreAggregateIds/pourEventStoreAggregateIds.unit.test.ts
- packages/lib-dam/src/pourEventStoreCollectionEvents/pourEventStoreCollectionEvents.ts
- packages/lib-dam/src/pourEventStoreCollectionEvents/pourEventStoreCollectionEvents.unit.test.ts
- packages/lib-dam/src/pourEventStoreEvents/pourEventStoreEvents.ts
- packages/lib-dam/src/pourEventStoreEvents/pourEventStoreEvents.unit.test.ts
- packages/lib-dam/src/types.ts
- packages/lib-dam/src/utils/eventBook.ts
- packages/lib-dam/src/utils/updateScanInfos.ts
- packages/lib-react-visualizer/src/tabs/DB/EventStoreDB.tsx
- packages/lib-test-tools/src/mockEventStore.unit.test.ts
- packages/lib-test-tools/src/muteEventStore.unit.test.ts
* Hardware:
* Toolchain:
* SDK:
> feature: return initialEventTimestamp in listAggregateIds method

- docs/docs/4-packages.md
- docs/docs/5-migration-guides/1-v1-to-v2.md
- docs/docs/5-migration-guides/_category_.json
- packages/lib-dam/README.md
* Hardware:
* Toolchain:
* SDK:
> docs: document migration from v1 to v2

- packages/core/src/event/eventType.ts
- packages/core/src/event/eventType.unit.test.ts
- packages/core/src/event/reservedEventTypes.ts
- packages/core/src/index.ts
- packages/event-type-json-schema/src/eventType.ts
- packages/event-type-json-schema/src/eventType.unit.test.ts
- packages/event-type-zod/src/eventType.ts
- packages/event-type-zod/src/eventType.unit.test.ts
- packages/message-bus-adapter-event-bridge/src/adapter.ts
- packages/message-bus-adapter-event-bridge/src/adapter.unit.test.ts
- packages/message-bus-adapter-event-bridge/src/message.ts
* Hardware:
* Toolchain:
* SDK:
> patch: prevent reserved event types

- packages/message-bus-adapter-event-bridge-s3/package.json
- packages/message-queue-adapter-sqs-s3/package.json
- yarn.lock
* Hardware:
* Toolchain:
* SDK:
> fix: increase undici vulnerable version

- .github/workflows/label-pr.yml
* Hardware:
* Toolchain:
* SDK:
> fix: edit label pr workflow
